### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by Kranzes** [hyperlight-dev/hyperlight#37]
Can you please remove Cargo.lock for gitignore and commit a Cargo.lock that's been verified to work with the crates?

**Comment by devigned** [comment]
Hyperlight is intended to be used as a library. I don't think we would want to check in the Cargo.lock since that would constrain folks taking a library dependency on the project.

**Comment by eddyb** [comment]
> Hyperlight is intended to be used as a library. I don't think we would want to check in the Cargo.lock since that would constrain folks taking a library dependency on the project.

Please see https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html, the official policy/recommendation on this matter has changed.

`Cargo.lock` in the git repo *does not* affect downstream users, but rather serves as a way to track known-working (as verified by CI) combinations of dependencies during development.

You can also add a "test after `cargo update`" step in CI, if you're concerned about issues arising from newer otherwise-semver-compat versions of dependencies etc.
